export const BEATFILM_BASE_URL = 'https://api.nomoreparties.co';
export const API_BASE_URL = 'https://amir.movies-explorer.nomoreparties.sbs/api';
export const errorMessage = 'Во время запроса произошла ошибка. Возможно, проблема с соединением или сервер недоступен. Подождите немного и попробуйте ещё раз';
export const nameRegex = /^[a-яёa-z -]+$/i
export const nameInvalidMessage = 'Имя может содержать только кириллицу, латиницу, пробел и дефис';
export const unauthorizedError = 'Вы ввели неправильный логин или пароль';
export const authError = 'При авторизации произошла ошибка';
export const userRegisterError = 'При регистрации пользователя произошла ошибка';
export const submitErrorMessage = 'Произошла ошибка';
export const serverError = 'На сервере произошла ошибка';
export const userDataUpdateError = 'При обновлении профиля произошла ошибка';
export const userDataUpdated = 'Данные успешно обновлены';
export const userEmailConflictError = 'Пользователь с таким email уже существует';